# Generated by Django 6.1.1 on 2026-09-21 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('IdUser', models.AutoField(db_column='IdUser', primary_key=True, serialize=False)),
                ('UserName', models.CharField(db_column='UserName', max_length=255, unique=True)),
                ('Password', models.CharField(db_column='Password', max_length=255)),
                ('Token', models.CharField(blank=True, db_column='Token', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
            },
        ),
    ]
